import { addDays, subDays } from "date-fns";

import type { Exercise, FeedComment, FeedPost, PhotoEntry, RunEntry, SessionUser, SwimEntry, WorkoutDay } from "@/types/app";

const today = new Date();
const videoSamples = [
  "https://samplelib.com/lib/preview/mp4/sample-5s.mp4",
  "https://samplelib.com/lib/preview/mp4/sample-10s.mp4",
  "https://samplelib.com/lib/preview/mp4/sample-15s.mp4",
];

export const demoUsers: SessionUser[] = [
  { id: "user-1", name: "Lia Costa", email: "lia@pulse.app", avatar: "LC", mode: "demo" },
  { id: "user-2", name: "Rafa Nunes", email: "rafa@pulse.app", avatar: "RN", mode: "demo" },
];

export const exerciseLibrary: Exercise[] = [
  {
    id: "supino-reto",
    name: "Supino reto",
    muscle: "peito",
    secondaryMuscles: ["triceps", "ombro anterior"],
    category: "hipertrofia",
    difficulty: "intermediario",
    equipment: "barra",
    isMachine: false,
    description: "Press horizontal para volume de peito com progressao clara de carga.",
    execution: "Escapulas firmes, punhos neutros e barra descendo no centro do peito.",
    mediaUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80",
    videoUrl: videoSamples[0],
    relatedIds: ["crucifixo-inclinado", "desenvolvimento-halter"],
  },
  {
    id: "crucifixo-inclinado",
    name: "Crucifixo inclinado",
    muscle: "peito superior",
    secondaryMuscles: ["ombro anterior"],
    category: "hipertrofia",
    difficulty: "iniciante",
    equipment: "halter",
    isMachine: false,
    description: "Abre o peito com amplitude controlada e foco em alongamento.",
    execution: "Cotovelo levemente flexionado, desce lento e sobe sem bater os halteres.",
    mediaUrl: "https://images.unsplash.com/photo-1598971639058-a0d4b2d4e995?auto=format&fit=crop&w=900&q=80",
    videoUrl: videoSamples[1],
    relatedIds: ["supino-reto", "pulley-frontal"],
  },
  {
    id: "agachamento-livre",
    name: "Agachamento livre",
    muscle: "quadriceps",
    secondaryMuscles: ["gluteo", "posterior", "core"],
    category: "forca",
    difficulty: "avancado",
    equipment: "barra",
    isMachine: false,
    description: "Base completa para forca e densidade de pernas.",
    execution: "Pe firme, coluna neutra e profundidade segura mantendo joelho alinhado.",
    mediaUrl: "https://images.unsplash.com/photo-1434682881908-b43d0467b798?auto=format&fit=crop&w=900&q=80",
    videoUrl: videoSamples[2],
    relatedIds: ["leg-press", "stiff"],
  },
  {
    id: "leg-press",
    name: "Leg press",
    muscle: "quadriceps",
    secondaryMuscles: ["gluteo"],
    category: "hipertrofia",
    difficulty: "iniciante",
    equipment: "maquina",
    isMachine: true,
    description: "Volume de perna com execucao estavel e progressao previsivel.",
    execution: "Desce controlado sem tirar o quadril do banco e empurra com o meio do pe.",
    mediaUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80",
    videoUrl: videoSamples[0],
    relatedIds: ["agachamento-livre", "supino-reto"],
  },
  {
    id: "desenvolvimento-halter",
    name: "Desenvolvimento",
    muscle: "ombro",
    secondaryMuscles: ["triceps", "trapezio"],
    category: "forca",
    difficulty: "intermediario",
    equipment: "halter",
    isMachine: false,
    description: "Press vertical para ombro com leitura simples de carga semanal.",
    execution: "Abdomen firme, cotovelos levemente a frente e subida em linha limpa.",
    mediaUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80",
    videoUrl: videoSamples[1],
    relatedIds: ["remada-baixa", "supino-reto"],
  },
  {
    id: "pulley-frontal",
    name: "Pulley",
    muscle: "costas",
    secondaryMuscles: ["biceps", "deltoide posterior"],
    category: "hipertrofia",
    difficulty: "iniciante",
    equipment: "cabo",
    isMachine: true,
    description: "Puxada vertical estavel para largura de dorsais.",
    execution: "Puxa com o cotovelo para baixo, peito aberto e sem balancar o tronco.",
    mediaUrl: "https://images.unsplash.com/photo-1571019613914-85f342c55f55?auto=format&fit=crop&w=900&q=80",
    videoUrl: videoSamples[2],
    relatedIds: ["remada-baixa", "rosca-direta"],
  },
  {
    id: "remada-baixa",
    name: "Remada",
    muscle: "costas",
    secondaryMuscles: ["biceps", "core"],
    category: "resistencia",
    difficulty: "intermediario",
    equipment: "cabo",
    isMachine: true,
    description: "Puxada horizontal com foco em densidade e estabilidade escapular.",
    execution: "Segura o tronco firme, finaliza com cotovelos atras e retorna lento.",
    mediaUrl: "https://images.unsplash.com/photo-1517960413843-0aee8e2b3285?auto=format&fit=crop&w=900&q=80",
    videoUrl: videoSamples[0],
    relatedIds: ["pulley-frontal", "desenvolvimento-halter"],
  },
  {
    id: "rosca-direta",
    name: "Rosca direta",
    muscle: "biceps",
    secondaryMuscles: ["antebraco"],
    category: "hipertrofia",
    difficulty: "iniciante",
    equipment: "barra",
    isMachine: false,
    description: "Isolamento direto de biceps para complementar puxadas.",
    execution: "Cotovelo preso, sobe sem roubar e desce mantendo tensao.",
    mediaUrl: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=900&q=80",
    videoUrl: videoSamples[1],
    relatedIds: ["pulley-frontal", "remada-baixa"],
  },
  {
    id: "corrida-leve",
    name: "Corrida leve",
    muscle: "cardio",
    secondaryMuscles: ["gluteo", "panturrilha"],
    category: "cardio",
    difficulty: "iniciante",
    equipment: "peso corporal",
    isMachine: false,
    description: "Base aerobica para consistencia semanal e recuperacao ativa.",
    execution: "Ritmo conversavel, passada curta e postura alta.",
    mediaUrl: "https://images.unsplash.com/photo-1486218119243-13883505764c?auto=format&fit=crop&w=900&q=80",
    videoUrl: videoSamples[2],
    relatedIds: ["nado-livre", "agachamento-livre"],
  },
  {
    id: "nado-livre",
    name: "Nado livre",
    muscle: "cardio",
    secondaryMuscles: ["costas", "ombro", "core"],
    category: "resistencia",
    difficulty: "intermediario",
    equipment: "peso corporal",
    isMachine: false,
    description: "Resistencia geral com baixo impacto articular.",
    execution: "Respiracao lateral regular, cotovelo alto e deslize consistente.",
    mediaUrl: "https://images.unsplash.com/photo-1519315901367-f34ff9154487?auto=format&fit=crop&w=900&q=80",
    videoUrl: videoSamples[0],
    relatedIds: ["corrida-leve", "remada-baixa"],
  },
];

export const workoutsSeed: WorkoutDay[] = [
  {
    id: "mon",
    label: "Seg",
    date: subDays(today, 1).toISOString(),
    kind: "gym",
    title: "Treino A",
    color: "#9CFF79",
    completed: true,
    durationMinutes: 68,
    tags: ["forca", "hipertrofia"],
    muscleGroups: ["peito", "ombro", "triceps"],
    quickNote: "Carga subiu no supino e manteve boa tecnica.",
    exercises: [
      { exerciseId: "supino-reto", sets: 4, reps: "8-10", weight: "72 kg", note: "ultimo set forte" },
      { exerciseId: "crucifixo-inclinado", sets: 3, reps: "12", weight: "18 kg" },
      { exerciseId: "desenvolvimento-halter", sets: 4, reps: "10", weight: "22 kg" },
    ],
  },
  {
    id: "tue",
    label: "Ter",
    date: today.toISOString(),
    kind: "run",
    title: "Run steady",
    color: "#4FD1FF",
    completed: true,
    durationMinutes: 43,
    tags: ["cardio", "resistencia"],
    muscleGroups: ["cardio", "core"],
    quickNote: "Ritmo constante na zona 2.",
    exercises: [{ exerciseId: "corrida-leve", sets: 1, reps: "6.4 km", weight: "43:12" }],
  },
  {
    id: "wed",
    label: "Qua",
    date: addDays(today, 1).toISOString(),
    kind: "gym",
    title: "Treino B",
    color: "#FF9D5C",
    completed: false,
    durationMinutes: 72,
    tags: ["hipertrofia"],
    muscleGroups: ["costas", "biceps"],
    quickNote: "Focar em amplitude na remada.",
    exercises: [
      { exerciseId: "pulley-frontal", sets: 4, reps: "10-12", weight: "55 kg" },
      { exerciseId: "remada-baixa", sets: 4, reps: "10", weight: "58 kg" },
      { exerciseId: "rosca-direta", sets: 3, reps: "12", weight: "28 kg" },
    ],
  },
  {
    id: "thu",
    label: "Qui",
    date: addDays(today, 2).toISOString(),
    kind: "swim",
    title: "Nado leve",
    color: "#76B8FF",
    completed: false,
    durationMinutes: 35,
    tags: ["resistencia"],
    muscleGroups: ["cardio", "costas", "ombro"],
    exercises: [{ exerciseId: "nado-livre", sets: 1, reps: "1.200 m", weight: "35 min" }],
  },
  {
    id: "fri",
    label: "Sex",
    date: addDays(today, 3).toISOString(),
    kind: "gym",
    title: "Treino C",
    color: "#C9A7FF",
    completed: false,
    durationMinutes: 78,
    tags: ["forca", "hipertrofia"],
    muscleGroups: ["quadriceps", "gluteo", "posterior"],
    quickNote: "Subir leg press e manter pausa no fundo.",
    exercises: [
      { exerciseId: "agachamento-livre", sets: 5, reps: "5", weight: "92 kg" },
      { exerciseId: "leg-press", sets: 4, reps: "12", weight: "220 kg" },
    ],
  },
];

export const feedSeed: FeedPost[] = [
  {
    id: "post-1",
    authorId: "user-1",
    authorName: "Lia Costa",
    avatar: "LC",
    type: "workout",
    caption: "Treino A limpo, supino subindo e ombro inteiro.",
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80",
    createdAt: subDays(today, 1).toISOString(),
    workoutMinutes: 68,
    likes: 19,
    likedByUserIds: [],
    streakDays: 14,
    consecutiveDays: 5,
    statsLabel: "68 min",
  },
  {
    id: "post-2",
    authorId: "user-2",
    authorName: "Rafa Nunes",
    avatar: "RN",
    type: "run",
    caption: "Ritmo steady, 6.4 km sem quebrar.",
    image: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1200&q=80",
    createdAt: today.toISOString(),
    workoutMinutes: 43,
    runKm: 6.4,
    runTime: "43:12",
    likes: 27,
    likedByUserIds: ["user-1"],
    streakDays: 9,
    consecutiveDays: 9,
    statsLabel: "6.4 km",
  },
  {
    id: "post-3",
    authorId: "user-1",
    authorName: "Lia Costa",
    avatar: "LC",
    type: "progress",
    caption: "Comparativo de 30 dias. Mais seco, mais denso.",
    image: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=1200&q=80",
    createdAt: subDays(today, 4).toISOString(),
    likes: 32,
    likedByUserIds: [],
    streakDays: 14,
    consecutiveDays: 5,
    statsLabel: "evolucao",
  },
  {
    id: "post-4",
    authorId: "user-2",
    authorName: "Rafa Nunes",
    avatar: "RN",
    type: "swim",
    caption: "Piscina curta, volume controlado e tecnica boa.",
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=80",
    createdAt: subDays(today, 2).toISOString(),
    swimDistance: 1200,
    workoutMinutes: 35,
    likes: 11,
    likedByUserIds: [],
    streakDays: 9,
    consecutiveDays: 9,
    statsLabel: "1.200 m",
  },
];

export const photoSeed: PhotoEntry[] = [
  {
    id: "photo-1",
    authorId: "user-1",
    image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1200&q=80",
    createdAt: subDays(today, 30).toISOString(),
    label: "30 dias",
    kind: "before-after",
    note: "Inicio do corte.",
  },
  {
    id: "photo-2",
    authorId: "user-1",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=80",
    createdAt: today.toISOString(),
    label: "Hoje",
    kind: "progress",
    note: "Mais definicao no tronco.",
  },
  {
    id: "photo-3",
    authorId: "user-2",
    image: "https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?auto=format&fit=crop&w=1200&q=80",
    createdAt: subDays(today, 12).toISOString(),
    label: "Track session",
    kind: "training",
  },
];

export const runSeed: RunEntry[] = [
  { id: "run-1", createdAt: subDays(today, 13).toISOString(), km: 4.8, meters: 0, time: "31:10" },
  { id: "run-2", createdAt: subDays(today, 7).toISOString(), km: 5.2, meters: 0, time: "33:40" },
  { id: "run-3", createdAt: today.toISOString(), km: 6.4, meters: 0, time: "43:12" },
];

export const swimSeed: SwimEntry[] = [
  { id: "swim-1", createdAt: subDays(today, 14).toISOString(), distance: 1000, time: "28:00" },
  { id: "swim-2", createdAt: subDays(today, 2).toISOString(), distance: 1200, time: "35:00" },
];

export const commentsSeed: Record<string, FeedComment[]> = {
  "post-1": [{ id: "comment-1", author: "Rafa", text: "Supino ficou muito solto hoje.", createdAt: today.toISOString() }],
  "post-2": [{ id: "comment-2", author: "Lia", text: "Ritmo ficou muito bom no km 4.", createdAt: today.toISOString() }],
};
